# Generated by Django 5.1 on 2024-08-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('average_before_normalization', models.FloatField()),
                ('average_after_normalization', models.FloatField()),
                ('data_size', models.IntegerField()),
                ('raw_data', models.JSONField()),
            ],
        ),
    ]
